services:
  - type: web
    name: metanoia-backend
    runtime: node
    buildCommand: cd backend && npm install && npx prisma generate && npx prisma db push --skip-generate --accept-data-loss
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PAGBANK_TOKEN
        sync: false
      - key: PAGBANK_API_URL
        value: https://api.pagseguro.com
      - key: PORT
        value: 10000
